image:
  repository: ghcr.io/pi-hole/pihole
  pullPolicy: IfNotPresent
  tag: 2025.08.0@sha256:90a1412b3d3037d1c22131402bde19180d898255b584d685c84d943cf9c14821
pihole:
  webPassword: "somepassword"
  dnsServers:
    - "9.9.9.9"
    - "149.112.112.112"
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    runAsUser: 0
    runAsGroup: 0
    capabilities:
      add:
        - NET_ADMIN
        - SETFCAP
        - SETPCAP
        - KILL
        - SYS_TIME
        - SYS_NICE
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - configMapRef:
                name: pihole-env
          probes:
            liveness:
              type: http
              path: /admin
            readiness:
              type: http
              path: /admin
            startup:
              type: http
              path: /admin
service:
  main:
    ports:
      main:
        port: 9089
        targetPort: 80
  dns:
    enabled: true
    ports:
      dns:
        enabled: true
        protocol: udp
        port: 53
        targetPort: 53
      dns-tcp:
        enabled: true
        protocol: tcp
        port: "{{ .Values.service.dns.ports.dns.port }}"
        targetPort: 53
persistence:
  config:
    enabled: true
    mountPath: "/etc/pihole"
  dnsmasq:
    enabled: true
    mountPath: "/etc/dnsmasq.d"
portal:
  open:
    enabled: true
